name: eventsource_core
description: A lightweight, flexible event sourcing framework for Dart
version: 0.1.0
repository: https://github.com/yourusername/eventsource_core

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.11.0
  collection: ^1.18.0
  async: ^2.11.0
  sqlite3: ^2.1.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
