name: eventsource_core
description: A lightweight, flexible event sourcing framework for Dart
version: 0.1.0
repository: https://github.com/yourusername/eventsource_core

environment:
  sdk: ^3.6.0

dependencies:
  meta: ^1.15.0
  collection: ^1.18.0
  async: ^2.11.0
  sqlite3: ^2.1.0
  synchronized: ^3.1.0
  ulid: ^2.0.1
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1 # Contains native libraries
  path_provider: ^2.1.2
  path: ^1.8.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  isar_generator: ^3.1.0+1
  analyzer: ^5.13.0
